// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cognito_identity_pool_id : 'us-east-1:9b93e80f-f6ce-4b55-8fef-3ec21684797d',
aws_cognito_region : 'us-east-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'magenameme-hosting-mobilehub-1757591791',
aws_content_delivery_bucket_region : 'us-east-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd2edis3of4vw98.cloudfront.net',
aws_mobile_analytics_app_id : '105e90d59e0c46a48cea4fc0f32754c2',
aws_project_id : '45f99d9d-6252-4564-93e6-28dc00aa6a71',
aws_project_name : 'Magename.me',
aws_project_region : 'us-east-1',
aws_resource_name_prefix : 'magenameme-mobilehub-1757591791',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});